#!/bin/bash
set -e

./install-awesome-terminal-fonts-v1.sh*
#./install-brackets-v1.sh*
#./install-caffeine-ng-v1.sh*
./install-cmatrix-git-v1.sh*
./install-conky-lua-archers-v1.sh*
./install-downgrade-v1.sh*
./install-etcher-bin-v1.sh*
./install-font-manager-git-v1.sh*
#./install-games-devices-udev-v1.sh*
./install-gitfiend-v1.sh*
./install-grub-customizer-v1.sh*
./install-hardcode-fixer-git-v1.sh*
./install-inxi-v1.sh*
./install-libreoffice-en-gb-v1.sh*
./install-mintstick-git-v2.sh*
./install-mpd-ncmpcpp-v3.sh*
./install-neofetch-v1.sh*
#./install-numix-circle-icon-theme-git-v1.sh*
#./install-numix-folders-git-v1.sh*
#./install-numix-kde-theme-git-v1.sh*
#./install-openbox-themes-pambudi-git-v1.sh*
#./install-oxy-neon-v1.sh*
#./install-paper-icon-theme-git-v1.sh*
#./install-papirus-icon-theme-git-v1.sh*
./install-peek-v1.sh*
./install-pkgcacheclean-v1.sh*
#./install-qemu-v1.sh*
#./install-radiotray-v1.sh*
#./install-sardi-extra-icons-v3.sh*
#./install-sardi-icons-v1.sh*
#./install-sardi-mint-y-icons-v1.sh*
./install-scrcpy-v1.sh*
#./install-snap-and-snap-store-v1.sh*
./install-stacer-v1.sh*
#./install-steam-amd-gpu-v1.sh*
#./install-steam-intel-gpu-v1.sh*
#./install-steam-nvidia-gpu-v1.sh*
#./install-sublime-text-v1.sh*
#./install-surfn-icons-git-v1.sh*
#./install-surfn-mint-y-icons-git-v1.sh*
./install-ttf-font-awesome-v1.sh*
./install-ttf-mac-fonts-v1.sh*
#./install-virtualbox-for-linux-lts-v2.sh*
#./install-virtualbox-for-linux-v2.sh*
#./install-vmworkstation-v2.sh*
